// import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    title: "Tshirts",
    Name: "SuperDry Black Tshirt",
    imageURL: "https://i.ibb.co/HNH3xzJ/Super-Dry-Tshirt-Black.jpg",
    id: "1",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 4.5,
  },
  {
    title: "Tshirts",
    Name: "SuperDry Grey Logo Tshirt",
    imageURL: "https://i.ibb.co/3cz0zzL/Super-Dry-Tshirt-Grey.jpg",
    id: "2",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 4.5,
  },
  {
    title: "Tshirts",
    Name: "CK T-Shirt Pink Tshirt",
    imageURL: "https://i.ibb.co/DYm1zmW/CK-Tshirt-Pink.jpg",
    id: "3",
    price: 599,
    orignalPrice: 700,
    category: "Tshirts",
    rating: 2.5,
  },
  {
    title: "Tshirts",
    Name: "SuperDry Pink Tshirt ",
    imageURL: "https://i.ibb.co/D9DYkFc/Super-Dry-Tshirt-Pink.jpg",
    id: "4",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 3.5,
  },
  {
    title: "Tshirts",
    Name: "Armani Tshirt Red",
    imageURL: "https://i.ibb.co/8x9N5xk/Super-Dry-Tshirt-Red.jpg",
    id: "5",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 4.5,
  },
  {
    title: "Tshirts",
    Name: "Osaka SuperDry Tshirt Off White",
    imageURL: "https://i.ibb.co/KFpJtjM/Super-Dry-Tshirt-Osaka.jpg",
    id: "6",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 4.5,
  },
  {
    title: "Tshirts",
    Name: " SuperDry Tshirt Blue",
    imageURL: "https://i.ibb.co/rw117S2/Super-Dry-Tshirt-Blue.jpg",
    id: "7",
    category: "Tshirts",
    price: 499,
    orignalPrice: 700,
    rating: 4.5,
  },
  {
    title: "Tshirts",
    Name: "SuperDry Tshirt Yellow",
    imageURL: "https://i.ibb.co/z5nH2mZ/Super-Dry-Tshirt-Yellow.jpg",
    id: "8",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 3.5,
  },
  {
    title: "Tshirts",
    Name: "SuperDry Tshirt Olive",
    imageURL: "https://i.ibb.co/jRW0SGS/Super-Dry-Tshirt.jpg",
    id: "9",
    category: "Tshirts",
    price: 599,
    orignalPrice: 700,
    rating: 4.5,
  },
  {
    title: "Jeans",
    Name: "Trouser Dark Grey",
    imageURL: "https://i.ibb.co/dWySPfL/Trouser-DG.jpg",
    id: "10",
    category: "Jeans",
    price: 899,
    orignalPrice: 999,
    rating: 4.5,
  },
  {
    title: "Jeans",
    Name: "Trouser 2",
    imageURL: "https://i.ibb.co/nr41Pmx/Trouser-2.jpg",
    id: "11",
    category: "Jeans",
    price: 899,
    orignalPrice: 999,
    rating: 4.5,
  },
  {
    title: "Jeans",
    Name: "Trouser Black",
    imageURL: "https://i.ibb.co/QvxwDkx/Trouser-Black.jpg",
    id: "12",
    category: "Jeans",
    price: 899,
    orignalPrice: 999,
    rating: 4.5,
  },
  {
    title: "Jeans",
    Name: "Trouser off white",
    imageURL: "https://i.ibb.co/X43hnMG/Trouser-OFF-White.jpg",
    id: "13",
    category: "Jeans",
    price: 899,
    orignalPrice: 999,
    rating: 4.5,
  },
  {
    title: "Shirts",
    Name: "Pista Shirt",
    imageURL: "https://i.ibb.co/7jfb7fy/pista-Shirt.jpg",
    id: "14",
    category: "Shirts",
    price: 699,
    orignalPrice: 899,
    rating: 4.0,
  },
  {
    title: "Shirts",
    Name: "Dark Blue Shirt",
    imageURL: "https://i.ibb.co/tZgPxsr/Dark-Blue-Shirt.jpg",
    id: "15",
    category: "Shirts",
    price: 699,
    orignalPrice: 899,
    rating: 4.0,
  },
  {
    title: "Shirts",
    Name: "Maroon Shirt",
    imageURL: "https://i.ibb.co/QNGpNxb/Maroon-Shirt.jpg",
    id: "16",
    category: "Shirts",
    price: 699,
    orignalPrice: 899,
    rating: 4.0,
  },
  {
    title: "Shirts",
    Name: "Purple Shirt",
    imageURL: "https://i.ibb.co/17h5nHh/Purple-Shirt.jpg",
    id: "17",
    category: "Shirts",
    price: 499,
    orignalPrice: 899,
    rating: 3.0,
  },
];
